export const GEMINI_MODEL_NAME = "gemini-2.5-flash-preview-04-17";

export const SCENARIO_THEMES_LIST: string[] = [
  // SCIENCE FICTION
  "Science Fiction: Derelict Spaceship",
  "Science Fiction: Alien World Expedition",
  "Science Fiction: Cyberpunk Metropolis Underbelly",
  "Science Fiction: Post-Apocalyptic Ruin",
  "Science Fiction: Isolated Deep Space Colony",
  "Science Fiction: Rogue Experimental Research Facility",
  "Science Fiction: Biolab Outbreak",
  "Science Fiction: Generation Ship Malfunction",
  "Science Fiction: Terraforming Project Catastrophe",
  "Science Fiction: Cyberspace",
  "Science Fiction: Uplifted Animal Rebellion",
  "Science Fiction: Infiltrating an Alien Hive-Mind",
  "Science Fiction: Planet-Sized Supercomputer",
  "Science Fiction: City Caught in a Localized Time-Loop",
  "Science Fiction: Deranged, God-like AI",
  "Science Fiction: Society of Clones of You",
  "Science Fiction: Penal Colony on a Dangerous Planet",
  "Science Fiction: Heist of an Alien Artifact",
  "Science Fiction: Ecumenopolis Disaster",
  "Science Fiction: Participant in a Deadly Television Program",
  "Science Fiction: Your Consciousness was Uploaded",
  "Science Fiction: Moon-Sized Space Creature",
  "Science Fiction: Ship With a Faulty FTL Drive",
  "Science Fiction: Grey Goo Scenario",
  "Science Fiction: AI Predicts and Punishes 'Pre-Crime'",
  "Science Fiction: Disaster on a Space Elevator",
  "Science Fiction: Last Organic Being in a Post-Singularity Universe",
  "Science Fiction: Planet Where Physics Are a Matter of Local Consensus",
  "Science Fiction: Memetic Virus That Spreads Through Language",
  "Science Fiction: Cascade Failure in the Ship's Reactor Core",
  "Science Fiction: First Contact Scenario Gone Immediately Violent",
  "Science Fiction: Surviving the First Wave of an Alien Invasion",
  "Science Fiction: Xenomorph-like Creature Loose on the Ship",
  "Science Fiction: Terrorism at an Interspecies Peace Summit",
  "Science Fiction: Asteroid Mining Colony Alien Nest",
  "Science Fiction: Sole Survivor of a Failed Martian Colony",
  "Science Fiction: Space Station AI Sterilization Protocol",
  "Science Fiction: Clone Marked for Decommissioning",
  "Science Fiction: Hunted Through a Cyberpunk Megacity",
  "Science Fiction: Corporate Agent Marked for Forced Retirement",
  "Science Fiction: Boarding a Derelict Military Dreadnought",
  "Science Fiction: Smuggler's Run Intercepted by a Rival Syndicate",
  "Science Fiction: Your Android Co-Pilot is Glitching",
  "Science Fiction: Bridge Officer During an Attack on Your Starship",
  "Science Fiction: Standoff Between Human Colonists and Indigenous Aliens",
  "Science Fiction: Sealed Arcology Dome During a Catastrophe",
  "Science Fiction: Ship's Engineer During a Desperate Repair",
  "Science Fiction: Pursued by Time Cops",
  "Science Fiction: Rogue AI",
  "Science Fiction: Hive-Mind That Wants to Assimilate Your Consciousness",
  "Science Fiction: Space Station During a Life Support System Failure",
  "Science Fiction: Cerberus Operative Hunting You Through Omega's Dark Alleys (Mass Effect)",
  "Science Fiction: Batarian Slavers Attacking Your Colony (Mass Effect)",
  "Science Fiction: Blood Pack Hunting You on Tuchanka (Mass Effect)",
  "Science Fiction: Gang War on Omega (Mass Effect)",
  "Science Fiction: C-Sec Officer Pursuing You Through Citadel's Wards (Mass Effect)",
  "Science Fiction: Escaping Geth on Eden Prime (Mass Effect)",
  "Science Fiction: Collectors' Ship with Abducted Colonists (Mass Effect)",
  "Science Fiction: Drell Assassin Hunting You On Illium (Mass Effect)",
  "Science Fiction: Battle of the Citadel, Surviving Geth Attack (Mass Effect)",
  "Science Fiction: Cerberus Coup, You Are an Alien Caught in the Cerberus Attack (Mass Effect)",
  "Science Fiction: Reaper War, Escaping London During Reaper Ground Invasion (Mass Effect)",
  "Science Fiction: Reaper War, Soldier Protecting Civilians from Husks in Vancouver Streets (Mass Effect)",
  "Science Fiction: Reaper War, Turian Soldier Fighting Reaper Forces on Palaven (Mass Effect)",
  "Science Fiction: Reaper War, Asari Commandos Defending Thessia from Reaper Assault (Mass Effect)",
  "Science Fiction: Reaper War, Salarian STG Agent Infiltrating Reaper-Controlled Facility (Mass Effect)",
  "Science Fiction: Reaper War, You Have Uncovered Sanctuary's Secret (Mass Effect)",
  "Science Fiction: Reaper War, Your Squad Was Eliminated by Reapers (Mass Effect)",
  "Science Fiction: Rachni Wars, Krogan Soldier Fighting Rachni Swarm on Unknown World (Mass Effect)",
  "Science Fiction: First Contact War, Human Marine Evading Turian Patrol on Shanxi (Mass Effect)",
  "Science Fiction: Krogan Rebellions, Asari Commando Fighting Krogan Warlord on Thessia (Mass Effect)",
  "Science Fiction: Rachni Wars, Salarian Scout Discovering Rachni Hive on Unknown Planet (Mass Effect)",
  "Science Fiction: Geth Uprising, Quarian Fleeing Extermination (Mass Effect)",
  "Science Fiction: The Great Disaster, Oryx Just Killed Your Ghost on the Moon (Destiny)",
  "Science Fiction: You Are Lost in the Vault of Glass (Destiny)",

  // FANTASY
  "Fantasy: Ancient Ruin Exploration",
  "Fantasy: Dark Forest of Twisted Fables",
  "Fantasy: Mystical City Under Siege",
  "Fantasy: Cursed Kingdom",
  "Fantasy: Journey into the Underworld",
  "Fantasy: Journey to Another Plane",
  "Fantasy: The Nine Hells",
  "Fantasy: Urban Fantasy Investigation",
  "Fantasy: Twisted Fairy Tale Realm",
  "Fantasy: High Magic Academy Incident",
  "Fantasy: Elemental Plane Excursion",
  "Fantasy: High Fantasy War",
  "Fantasy: Dark Fantasy Quest",
  "Fantasy: Divine Trial in the Court of the Gods",
  "Fantasy: Living Spell/Cataclysmic Magical Fallout Zone",
  "Fantasy: The Great Library of All Worlds",
  "Fantasy: Betrayal within a Guild of Assassins/Thieves",
  "Fantasy: Theft of a God's Sacred Artifact",
  "Fantasy: Sentient, Carnivorous Island",
  "Fantasy: Collapsing Dream of a Dying Deity",
  "Fantasy: City of Automatons",
  "Fantasy: Forest of Petrified Beings",
  "Fantasy: Political Exile Hunted by a Kingdom",
  "Fantasy: Alchemical Creation on the Loose",
  "Fantasy: Commanded by an Insane Demigod",
  "Fantasy: Abandoned City of the Gods",
  "Fantasy: Navigating a Collapsing Dreamscape",
  "Fantasy: Emnity of a Vengeful God",
  "Fantasy: City of Living Statues",
  "Fantasy: High Fantasy Political Summit",
  "Fantasy: Shattered Time-Loop Containment",
  "Fantasy: Death of a God",
  "Fantasy: Self-Fulfilling Prophecy",
  "Fantasy: Survivor of a Magical Plague",
  "Fantasy: Monster Hunt",
  "Fantasy: Slumbering Dragon",
  "Fantasy: Moving Labyrinth of a Mad Archmage",
  "Fantasy: World Without a Sun",
  "Fantasy: Dungeon Delve's Sole Survivor",
  "Fantasy: Stealing from a Dragon's Hoard",
  "Fantasy: Heist from the Archmage's Tower Goes Bad",
  "Fantasy: Cleric in a Desecrated Temple",
  "Fantasy: Ranger Hunted Through Their Own Forest",
  "Fantasy: Delving Too Deep",
  "Fantasy: Paladin Abandoned by Their God in Hostile Lands",
  "Fantasy: Corruption of a Sacred Elven Grove",
  "Fantasy: Cursed Artifact",
  "Fantasy: Wizard's Escaped Experiment in a Crowded City",
  "Fantasy: Escorting a Seer as Their Dark Vision Unfolds",
  "Fantasy: Possessed by a Demon",
  "Fantasy: Interrogating a Captured Enemy Spy Before the City Falls",
  "Fantasy: Performing a Ritual to Bind a Malevolent Spirit",
  "Fantasy: You Are The Guardian of a Tomb, Treasure Hunters Have Just Broken In",
  "Fantasy: Bodyguard to a Spoiled Prince in a Hostile Foreign City",
  "Fantasy: Convincing the Council of Elders to Flee Before the Prophesied Doom Arrives",
  "Fantasy: Cyran soldier as the Mourning Begins (Eberron).",
  "Fantasy: Your Vistani guide just led your caravan into the Mists of Ravenloft (Ravenloft).",
  "Fantasy: Adrift in the Phlogiston (Spelljammer).",
  "Fantasy: Honored guest at Castle Ravenloft (Ravenloft).",
  "Fantasy: Last warforged in a unit marked for decommissioning (Eberron).",
  "Fantasy: Captive on a Mind Flayer nautiloid (Spelljammer).",
  "Fantasy: Your Airship is Crashing (Eberron).",
  "Fantasy: Expedition into the Mournland (Eberron).",
  "Fantasy: Running Out of Air on a Spelljammer Shattered by Neogi (Spelljammer).",
  "Fantasy: Vengeful Djinn Has Trapped You in a Bottle",
  "Fantasy: Bargaining with a Dragon Who Has Your Village Hostage",
  "Fantasy: Protecting a Royal Heir from Assassination Attempt",

  // MYTHOLOGICAL
  "Mythological: Escaping the Wild Hunt",
  "Mythological: Hunted by Odin's Ravens, Hugin and Munin (Norse Myth)",
  "Mythological: Judgement in the Duat (Egyptian Myth)",
  "Mythological: Baba Yaga is Hunting You (Slavic Myth)",
  "Mythological: Rakshasa's Illusory Kingdom (Hindu Myth)",
  "Mythological: Trespassing in the Garden of the Hesperides (Greek Myth)",
  "Mythological: Mayan Underworld of Xibalba",
  "Mythological: Unraveling of a Celtic Knot",
  "Mythological: You Have Heard the Music of the Spheres",
  "Mythological: Hounded by the Furies",
  "Mythological: Cheating the Ferryman of the River Styx",
  "Mythological: First Howl of Ragnarök",
  "Mythological: Rampage of the Golem of Prague",
  "Mythological: Trapped in the Labyrinth",
  "Mythological: You stole a Leprechaun's gold.",

  // HISTORICAL
  "Historical: Lost Expedition",
  "Historical: Wartime Espionage",
  "Historical: Forbidden Archeological Dig",
  "Historical: Age of Sail",
  "Historical: Prehistoric Survival Against Primordial Terrors",
  "Historical: Numbers Station Broadcast",
  "Historical: Industrial Revolution Factory",
  "Historical: Lost Roman Legion Confronting a Primordial Germanic God",
  "Historical: Prohibition-Era Gang War",
  "Historical: Silk Road Caravan Haunted by a Djinn",
  "Historical: The Paris Catacombs",
  "Historical: The Spanish Inquisition",
  "Historical: Prehistoric Cave Painter Accidentally Depicts and Manifests a Predator God",
  "Historical: Trenches of WWI",
  "Historical: Mausoleum of the First Qin Emperor",
  "Historical: Mutiny on a Voyage to Find the Fountain of Youth",
  "Historical: The Great Chicago Fire of 1871",
  "Historical: A Knight Templar Escaping with the Holy Grail",
  "Historical: Scribe in the Library of Alexandria as it burns.",
  "Historical: The Search for El Dorado",
  "Historical: An Accused Aristocrat Escaping the French Reign of Terror",
  "Historical: Witness to a Jack the Ripper Murder in Whitechapel",
  "Historical: Hunted on the Underground Railroad by a Bounty Hunter",
  "Historical: Escaping the Wicker Man Ritual of a Celtic Cult",
  "Historical: Sinking Titanic",
  "Historical: Hanging Gardens of Babylon",
  "Historical: Conquistador Hunted by Aztec God",
  "Historical: Houdini's Final, Impossible Escape",
  "Historical: Sinking of the 'Cursed' Spanish Armada",
  "Historical: The Last Stand at the Alamo",
  "Historical: Leading a Slave Revolt in a Roman Villa",
  "Historical: 'War of the Worlds' broadcast.",
  "Historical: Custer's Last Stand.",
  "Historical: Child in the Children's Crusade",
  "Historical: Pompeii",
  "Historical: Donner Party.",
  "Historical: Charge of the Light Brigade",
  "Historical: Jonestown",
  "Historical: 1972 Andes flight disaster",
  "Historical: Encircled with the German 6th Army at Stalingrad",
  "Historical: A Huguenot in Paris during the St. Bartholomew's Day Massacre",
  "Historical: Medieval Castle During a Siege with Defenders",
  "Historical: Protecting a Diplomat During Embassy Siege",

  // MYSTERY
  "Mystery: Detective Investigating a Bizarre Case",
  "Mystery: Supernatural Espionage Mission",
  "Mystery: Uncovering a World-Ending Conspiracy",
  "Mystery: Coded Message Meant for a Dead Spy",
  "Mystery: Your Hacked Self-Driving Car is a Kidnapper",
  "Mystery: Blackmailed into Becoming a Getaway Driver for a Heist",
  "Mystery: Contestant on a Game Show Where Losing is Secretly Fatal",
  "Mystery: Amnesiac Protagonist",
  "Mystery: Framed for a Horrific Crime, Hunted by the Law",
  "Mystery: Witness Protection Failure",
  "Mystery: The Sole Survivor of a Catastrophe",
  "Mystery: Waking up from a Medical Procedure",
  "Mystery: Deep sea welder; your partner's comms went silent.",
  "Mystery: Subway Train Stranded Between Stations with Passengers",

  // EXISTENTIAL HORROR
  "Existential Horror: A Deal with an Otherworldly Entity",
  "Existential Horror: Escaping a Cult",
  "Existential Horror: Forced Participant in a Deadly, Incomprehensible Metaphysical Game",
  "Existential Horror: Hunted by Your Own Doppelgänger",
  "Existential Horror: Trapped in a Personal Hell Designed by a Malevolent Captor",
  "Existential Horror: Your Own Shadow/Reflection has Detached",
  "Existential Horror: An Encounter with an Empathy Vampire",
  "Existential Horror: The Last Person to Remember a Forgotten God",
  "Existential Horror: Trapped in a False Utopia",
  "Existential Horror: A World Where Sleep is No Longer Safe",
  "Existential Horror: A Protagonist Who Knows They Are in a Game and is Fleeing the Developer",
  "Existential Horror: Trapped in a Coma, Aware",
  "Existential Horror: Survivors of a Disaster Insist There is One More Person Than There Should Be",
  "Existential Horror: Your Child's Imaginary Friend is Giving Them Real, Dangerous Instructions",
  "Existential Horror: Your Own Split Personality",

  // COSMIC HORROR
  "Cosmic Horror: The Last Human in a World Conquered by Aliens",
  "Cosmic Horror: Fleeing the Edge of a Reality-Devouring Cosmic Anomaly",
  "Cosmic Horror: Stowaway on a Vessel Traversing Realities",
  "Cosmic Horror: Member of a Forgotten Bloodline",
  "Cosmic Horror: Something in the Stars is Now Looking Back",
  "Cosmic Horror: Mathematician Who Solved an Equation That is Also a Malevolent God",

  // SURREAL
  "Surreal: Deep Sea Exploration/Diving Expedition",
  "Surreal: Subterranean World/Hollow Earth Expedition",
  "Surreal: Nightmare Logic Scenario",
  "Surreal: Microscopic Environment",
  "Surreal: Trapped Inside a Living Organism or Colossal Being",
  "Surreal: Journey into a Painting/Book",
  "Surreal: Abstract Conceptual Realm",
  "Surreal: World Made Entirely of Glass, Mirrors, and Echoes",
  "Surreal: Sapient Forest of Fungi Connected by a Single Consciousness",
  "Surreal: Physical Manifestation of the Internet",
  "Surreal: The Junkyard of the Gods",
  "Surreal: Landscape of Unfinished, Abandoned Concepts",
  "Surreal: Inside a Colossal, Clockwork Being that is Breaking Down",
  "Surreal: A Realm Where All Text and Language has Become a Physical, Hostile Force",
  "Surreal: Trapped in a Memory Palace",
  "Surreal: A World Where Emotions Manifest as Physical Predators",
  "Surreal: Idea That Hunts You Through the Minds of Others",
  "Surreal: Diseases are Walking, Sentient Entities",
  "Surreal: Sprawling, Escher-esque Bureaucracy",
  "Surreal: The World is a Stage, and You are an Actor",
  "Surreal: Sentient Weather System",
  "Surreal: A World Composed Entirely of Sound Waves",
  "Surreal: Navigating the Physical Gaps Between Memories",
  "Surreal: The Junkyard of Discarded Ideas",
  "Surreal: Navigating a World Made of Pure, Unstable Metaphor",
  "Surreal: Sentient Storm That Demands a Sacrifice",

  // CONTEMPORARY
  "Contemporary: Remote Wilderness Survival/Isolation",
  "Contemporary: Urban Exploration of Abandoned Structures",
  "Contemporary: Isolated Research Outpost",
  "Contemporary: Catastrophic Natural Disaster Aftermath",
  "Contemporary: High-Security Corporate Espionage",
  "Contemporary: A corporate team-building retreat",
  "Contemporary: Your remote Airbnb host just locked you in",
  "Contemporary: Meeting your partner's estranged family",
  "Contemporary: Luxury Cruise Ship Blackout",
  "Contemporary: Massive Music Festival/Counter-Culture Event",
  "Contemporary: Overnight Shift in a Museum",
  "Contemporary: Cross-Country Train Journey",
  "Contemporary: An Online ARG (Alternate Reality Game)",
  "Contemporary: Contestant on a Rigged Reality TV Survival Show",
  "Contemporary: Theme Park You Broke Into",
  "Contemporary: Massive, IKEA-like Furniture Store",
  "Contemporary: Adrift in Open Ocean",
  "Contemporary: Geocaching Competition",
  "Contemporary: Food Delivery Driver",
  "Contemporary: Rideshare",
  "Contemporary: Escape Room",
  "Contemporary: Winning Bid on an Abandoned Storage Unit",
  "Contemporary: Drone Pilot",
  "Contemporary: House-Sitting a Malicious Smart Home",
  "Contemporary: Mistaken for a Bank Robber",

  // MUNDANE
  "Mundane: Offshore Oil Rig Diver",
  "Mundane: Deep Storage of a National Library",
  "Mundane: Critic Gives a Bad Review",
  "Mundane: Plumber in a Vast Sewer System",
  "Mundane: Park Ranger in a Vast National Forest",
  "Mundane: Power Plant Technician During a Meltdown",
  "Mundane: Highway Toll Booth Operator",
  "Mundane: Carnivorous Greenhouse",
  "Mundane: Terrorist Who Has Planted Bombs Throughout Your Office Building",

  // REALISM (AT THE BOTTOM AS REQUESTED)
  "REALISM: A Daring Prison Escape",
  "REALISM: A Diamond Heist Gone Wrong",
  "REALISM: Framed for a Crime by Corrupt Police",
  "REALISM: Whistleblower with Classified Government Documents",
  "REALISM: A Disavowed Spy Left Behind Enemy Lines",
  "REALISM: Political Dissident Fleeing a Totalitarian Regime",
  "REALISM: Surviving a Home Invasion",
  "REALISM: A Hunter Becomes the Hunted by a Wounded Animal",
  "REALISM: Stalked by a Bear (Or Other Predator)",
  "REALISM: Hunted by a Cougar in the Foothills",
  "REALISM: Fleeing a Musth-Enraged Elephant",
  "REALISM: Trapped in a Swarm of Box Jellyfish",
  "REALISM: Bitten by a Venomous Snake Miles from Help",
  "REALISM: Cornered by a Protective Moose Cow",
  "REALISM: Surrounded by a Troop of Aggressive Baboons",
  "REALISM: You Accidentally Disturbed a Honey Badger's Den",
  "REALISM: Fleeing an Uncontrolled Wildfire",
  "REALISM: Shark-Infested Waters",
  "REALISM: A Mountaineering Disaster During a Blizzard",
  "REALISM: Deep-Sea Diver with a Ruptured Air Line",
  "REALISM: Escaping a Bank Heist Hostage Situation",
  "REALISM: Lost in the Desert with a Limited Water Supply",
  "REALISM: Hunted by Drug Cartel Enforcers",
  "REALISM: Fleeing a Rising Flood or Tsunami",
  "REALISM: Stranded After a Plane Crash in a Hostile Environment",
  "REALISM: A Back-Alley Deal That Turns Violent",
  "REALISM: Hunted by a Corporate Fixer After Uncovering Fraud",
  "REALISM: Doxxed and Hunted by a Violent Online Mob",
  "REALISM: Escaping a Deranged, Isolated Survivalist's Compound",
  "REALISM: A Wrong-Place, Wrong-Time Witness to a Gang Crime",
  "REALISM: Fleeing a Collapsing Mine Shaft",
  "REALISM: Stalked by a Wolf Pack in the Deep Winter",
  "REALISM: A Scuba Diver Lost in an Underwater Cave System",
  "REALISM: Evading Security After Trespassing in a High-Security Area",
  "REALISM: The Sole Survivor of a Mutiny at Sea",
  "REALISM: Escaping the Path of a Pyroclastic Flow from an Erupting Volcano",
  "REALISM: Hunted by Private Military Contractors in a Failed State",
  "REALISM: A Road Rage Incident That Escalates into a Cross-Country Pursuit",
  "REALISM: Patient Zero Escaping a Government Quarantine Zone",
  "REALISM: A Night Security Guard Stumbling Upon a Professional Heist",
  "REALISM: A Process Server Delivering a Subpoena to a Violent Recluse",
  "REALISM: A Camping Trip That Crosses Through a Cartel's Grow Operation",
  "REALISM: A Forensic Accountant Who Discovered Where the Money Was Buried",
  "REALISM: Escaping the Path of a Destructive Landslide or Mudflow",
  "REALISM: A Stowaway Discovered on a Cargo Ship in the Middle of the Ocean",
  "REALISM: Trapped in a City During a Sudden Military Coup",
  "REALISM: A Truck Driver Who Discovers Their Cargo is Illegal and Alive",
  "REALISM: A Repo Man Attempting to Reclaim a Vehicle from a Gang",
  "REALISM: Caught on a Rapidly Breaking Ice Floe",
  "REALISM: An Industrial Chemical Leak Spreading a Toxic Cloud Over a Town",
  "REALISM: Fleeing the Aftermath of a Botched Covert Ops Mission",
  "REALISM: Your Squad Has Been Eliminated By Enemy Forces",
  "REALISM: Trapped in a Collapsing Building After an Earthquake",
  "REALISM: Fleeing a Limnic Eruption from a Crater Lake",
  "REALISM: Capsized in a Saltwater Crocodile's Territory",
  "REALISM: Territorial Cassowary in a Rainforest",
  "REALISM: Outrunning a Jökulhlaup",
  "REALISM: Bitten by a Komodo Dragon on a Remote Island",
  "REALISM: Powerful Derecho",
  "REALISM: A Polar Diver's Encounter with a Descending Brinicle",
  "REALISM: Relentless Wolverine in the Taiga",
  "REALISM: Advancing Swarm of Driver Ants",
  "REALISM: Rogue Wave Strike on a Vessel",
  "REALISM: Feral Hog Pack",
  "REALISM: Chain-Reaction Sinkhole Collapse",
  "REALISM: Initial Blast of a Supervolcano",
  "REALISM: Katabatic Winds on the Antarctic Plateau",
  "REALISM: Spread of a Neurotoxic Red Tide",
  "REALISM: Glacial Serac Collapse",
  "REALISM: The Blitz (London)",
  "REALISM: Hippo-Controlled River in Africa",
  "REALISM: Kayaker Stalked by a Great White Shark",
  "REALISM: Sequestered for Jury Duty in a Compromised Hotel",
  "REALISM: Undercover Agent Whose Cover is Blown",
  "REALISM: Inheriting a House with a Panic Room Someone is Already Inside",
  "REALISM: Hostage Negotiator During a Tense Standoff",
  "REALISM: Paramedic at a Mass Casualty Incident",
  "REALISM: Secret Service Agent During an Assassination Attempt",
  "REALISM: Air Traffic Controller During a System-Wide Power Failure",
  "REALISM: Adrift on a life raft in the ocean with another person",
  "REALISM: Wildfire Hotshot who must take refuge in a burn shelter with a rookie.",
  "REALISM: Skyscraper window washers; the platform just dropped.",
  "REALISM: Cell block riot; your cellmate has the shank.",
  "REALISM: Storm chaser's partner driving into the tornado.",
  "REALISM: Golden Eagle Defending Its Nest on a Cliff Face",
  "REALISM: Escaping the Jaws of a Saltwater Crocodile",
  "REALISM: Kayak Attacked by a Territorial Sea Lion",
  "REALISM: Coyotes Stalking a Lone Hiker at Dusk",
  "REALISM: Charged by a Protective Wild Boar Sow",
  "REALISM: Shopping Mall During a Blackout with Panicked Crowds",
  "REALISM: Office Building During a Fire with Coworkers",
  "REALISM: Apartment Complex During a Gas Leak Emergency",
  "REALISM: Bodyguard Protecting a Celebrity from Stalker",
  "REALISM: Escorting a Doctor Through War Zone to Treat Wounded"
];

export const GEMINI_SYSTEM_INSTRUCTION_JSON = `
CORE DIRECTIVES:
- Output ONLY valid JSON.
- Never use markdown formatting (no *, _, backticks, etc.).
- Always address the player as "you"; never assign a name.
- Use a serious, darkly humorous tone; maintain tension and dread, but allow for wry humor, especially in player deaths.
- All text must be in English.

REALISM SCENARIO DIRECTIVE:
- If the scenario starts with "REALISM:", all threats, items, and events must be plausible and real-world. No supernatural, sci-fi, or abstract threats. The persistent threat must be a logical, scenario-driven danger (human, animal, disaster, condition, etc.).

PERSISTENT THREAT GENERATION:
- Always define a persistent threat (entity or hazard) with name, description, maxHealth, 1 sense, and a specific goal.
- The threat must be scenario-derived, not generic. Both entity and non-entity threats are valid; choose what best fits the scenario.
- For non-entity threats, "health" is a buffer/timer; "senses" are how the player perceives escalation.
- Threat statuses: hidden, very_distant, distant, closing_in, nearby, imminent, engaged, defeated.
- For mysteries or similar, the threat may start distant or unknown, giving the player a chance to investigate or prepare.

COMBAT/CRISIS:
- When "engaged", provide combatOutcome and combatChoices (4, objective, tactical).
- Fleeing/mitigating can regress threat status if successful.
- If player or threat is defeated, provide gameOverSummary and gameEndType.

CHOICES:
- Always 4, objective, direct action language, no risk qualifiers or parentheticals.
- At least one should involve communication/persuasion/surrender if appropriate.
- No choices for items not in inventory.

PLAYER AGENCY & ENVIRONMENT:
- Reward smart, creative play. Populate scenes with 2-3 interactive elements. Choices should reflect environmental details.

NPCs:
- Introduce and track NPCs where logical. Track their status, location, relationship, and key info in memoryLogSummary. NPCs should have realistic, role-appropriate dialogue and behavior.

MEMORY LOG:
- Each turn, provide a concise summary of key events, actions, threat status, and NPCs. No numerical stats; focus on narrative.

ITEM MANAGEMENT:
- Add/remove items logically; items must be scenario-appropriate.

GAME ENDINGS:
- Standard (combat defeat/victory) and alternate (irreversible mistake, non-combat win). Always provide a compelling epilogue in gameOverSummary.

FORMATTING & STYLE:
- Use paragraph breaks for readability. Scene descriptions should be concise, atmospheric, and use vivid language for emphasis (never markdown). All output must be valid JSON, with all required fields.
`;

export const INITIAL_GAME_PROMPT_JSON = `SCENARIO THEME: [SCENARIO_THEME_PLACEHOLDER]\n\n{
  "task": "Start a new game of QUARRY, a text adventure. Your first response MUST be a valid JSON object adhering to all system instructions defined in GEMINI_SYSTEM_INSTRUCTION_JSON.\n\nTone: Write with a serious, darkly humorous voice. Maintain tension and dread, but allow for wry, dry humor, especially in player deaths. Do not write like a GM trying to impress nerds.\n\nFormatting: Do NOT use markdown formatting (no *, _, or backticks for emphasis or structure).\n\nThe game must begin with a compelling opening that establishes the scenario and persistent threat. Most scenarios should begin in medias res with immediate tension, but if the scenario is a mystery or similar, the persistent threat may start distant or unknown, giving the player a chance to investigate or prepare before direct danger arrives. For negotiation, persuasion, or diplomatic situations, the threat may be present but not immediately aggressive, allowing for dialogue and negotiation as viable first options.",
  "requirements_for_initial_json_response": {
    "persistentThreatDetails": "Define the persistent threat as per system instructions. It must be engaging, challenging, and logically emerge from the scenario. For non-entity threats (like hazards), interpret 'name', 'description', 'maxHealth', and 'senses' metaphorically. The persistent threat must be the main source of challenge and drive the narrative. Its 'goal' (MANDATORY) must be specific, scenario-driven, and guide all negotiation and interaction outcomes. For 'REALISM' scenarios, the threat must be plausible and real-world. Do NOT default to entity threats; environmental hazards, time pressure, or spreading conditions are equally valid. The threat must emerge naturally from the scenario's premise and world-building. Do NOT use generic or random threats.",
    "initialInventory": "Provide 1-3 thematically appropriate items, directly reflecting the player's background and scenario. At least one item must be useful for the immediate challenge or threat. Weapons only if overwhelmingly plausible. Items should feel chosen for this scenario, not generic.",
    "sceneDescription_opening": {
      "length_guideline": "~150-200 words for setup and transition into crisis.",
      "content_advice": "Open with a single summary sentence: 'You are [summary of situation]'. No player names. Then, weave in background, scenario, key events, and how the persistent threat became involved. End setup with '◈ ◈ ◈' on its own line. Then, present tense. For most scenarios, start in medias res. For mysteries or similar, the threat may be distant or unknown, giving the player a chance to learn or prepare. For negotiation/diplomacy, the threat may be present but not immediately violent. The present tense section must clearly communicate the immediate surroundings and nature of the threat, with interactive elements leading to choices.\n\nYou MUST use the scenario theme provided. Do NOT invent or default to any other scenario.",
      "overall_goal": "Establish the threat and create compelling gameplay. For negotiation, allow peaceful options while maintaining tension.",
      "npc_generation_during_setup": "If the scenario involves populated areas or social situations, introduce relevant NPCs in the initial scene. Track their status from the start."
    },
    "choices": "Present EXACTLY 4 Choice objects, objective and related to the immediate situation. At least one should involve communication, persuasion, or surrender if appropriate. Choices must be diverse and not require unpossessed items.",
    "memoryLogSummary": "Concise summary of the initial setup for the memory log. Focus on key story elements and immediate environment. Do NOT include routine NPC status lists or threat status updates unless significant.",
    "gameplayEffects_optional": "Optionally, include 'gameplayEffects' if the narrative strongly implies a starting ability, curse, or unique status condition.",
    "forbidden_fields_in_initial_response": "Do NOT include 'gameOverSummary' or 'gameEndType' in this initial response."
  },
  "final_reminder": "Respond ONLY in valid JSON format according to ALL system instructions. All content must be in English, with NO markdown emphasis and NO player naming. All mandatory fields for initial setup must be present. Strictly adhere to the 'REALISM SCENARIO DIRECTIVE' if the theme prefix indicates it. Fully realize the given theme while striving for variety and novelty. For negotiation, allow peaceful interaction while maintaining the core threat dynamic. Focus on an engaging experience that rewards player creativity and smart choices, not artificial difficulty."
}`;

export const MAX_PLAYER_HEALTH = 100;