name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "Build Step: Creating temporary environment file at ./services/env.js"
            # Create env.js inside the services/ directory to match the import path.
          echo "export const API_KEY = '${{ env.API_KEY }}';" > env.js
          echo "Build Step: Executing esbuild command..."
          npx esbuild index.tsx \
            --bundle \
            --outfile=bundle.js \
            --platform=browser \
            --format=esm \
            --minify \
            --external:react \
            --external:react-dom/client \
            --external:react/jsx-runtime \
            --external:@google/genai
          echo "Build Step: esbuild command finished."

      - name: Verify Build Correctness
        # This check is still valuable. It will now fail if you forget to
        # remove 'process.env.API_KEY' from your application code.
        run: |
          if grep -q "process.env.API_KEY" bundle.js; then
            echo "Error: Build failed. 'process.env.API_KEY' was found literally in bundle.js."
            echo "This likely means you haven't updated your JS/TS code to import the key from src/env.js."
            exit 1
          else
            echo "Success: 'process.env.API_KEY' was not found in the bundle."
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4